apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: mariadb-cluster
data:
  galera.cnf: |
    [mysqld]
    wsrep_on=ON
    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_name="mariadb_cluster"
    wsrep_cluster_address="gcomm://mariadb-0.mariadb.mariadb-cluster.svc.cluster.local,mariadb-1.mariadb.mariadb-cluster.svc.cluster.local,mariadb-2.mariadb.mariadb-cluster.svc.cluster.local"
    wsrep_node_name=mariadb-0
    wsrep_node_address=mariadb-0.mariadb.mariadb-cluster.svc.cluster.local
    wsrep_sst_method=rsync
    binlog_format=row
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    innodb_doublewrite=1
    innodb_flush_log_at_trx_commit=2
